#!/usr/bin/env python3
"""Generate RESEARCH_STATUS.md from committed machine-readable research state.

This file is intentionally derived from authoritative artifacts so human status
prose cannot silently lag the evidence matrix, runtime queue, foundation report,
or tooling incident ledger.
"""
from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(".")
OUT = ROOT / "RESEARCH_STATUS.md"


def load(name: str) -> dict:
    path = ROOT / name
    if not path.exists():
        raise SystemExit(f"Missing required status input: {name}")
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> None:
    integrity = load("04_BEHAVIOR_INTEGRITY.json")
    coverage = load("04_BEHAVIOR_COVERAGE.json")
    queue = load("04_RUNTIME_OBSERVATION_QUEUE.json")
    foundation = load("00_FOUNDATION_INTEGRITY.json")
    tooling = load("00_TOOLING_FAILURE_LEDGER.json")

    frozen = integrity.get("frozen_commit")
    if not frozen or frozen != queue.get("frozen_commit") or frozen != foundation.get("baseline", {}).get("frozen_commit"):
        raise SystemExit("Research status inputs disagree on frozen commit")

    hard_errors = []
    hard_errors.extend(integrity.get("hard_errors", []))
    hard_errors.extend(coverage.get("hard_errors", []))
    hard_errors.extend(queue.get("hard_errors", []))
    hard_errors.extend(foundation.get("hard_errors", []))
    if hard_errors:
        raise SystemExit(f"Cannot publish research status with hard errors: {hard_errors}")

    observed = int(integrity["runtime_observed_count"])
    rows = int(integrity["row_count"])
    pending = int(queue["pending_total"])
    if observed + pending != rows:
        raise SystemExit("Runtime observed + pending does not equal behavior denominator")

    pending_by = queue.get("pending_by_class", {})
    observed_by = queue.get("observed_by_class", {})
    state_counts = integrity.get("state_counts", {})
    machine_counts = integrity.get("machine_enforced_counts", {})
    note_status = foundation.get("note_status_counts", {})

    lines = [
        "# Research Status",
        "",
        "## Project state",
        "",
        "**IN PROGRESS**",
        "",
        "Source repository: `mattpocock/skills`  ",
        f"Frozen commit: `{frozen}`  ",
        f"Physical denominator: **{foundation.get('baseline', {}).get('physical_files', 0)} blobs/files**",
        "",
        "## Storage authority",
        "",
        "This GitHub repository is the authoritative project state. Chat history, memory, summaries, and transient tool output are not authoritative storage.",
        "",
        "Machine-readable artifacts outrank this human checkpoint if they ever disagree. `RESEARCH_STATUS.md` is generated by `scripts/build_research_status.py`, and the Phase 4 main guard fails when the committed checkpoint is stale.",
        "",
        "## Foundation",
        "",
        f"- durable file notes: **{foundation.get('note_count', 0)}/{foundation.get('baseline', {}).get('physical_files', 0)}**;",
        f"- `CONNECTIONS TRACED`: **{note_status.get('CONNECTIONS TRACED', 0)}/{foundation.get('baseline', {}).get('physical_files', 0)}**;",
        f"- hard integrity errors: **{len(foundation.get('hard_errors', []))}**;",
        f"- warnings: **{len(foundation.get('warnings', []))}**;",
        f"- current contradiction IDs: **{len(foundation.get('contradiction_ids_current', []))}**;",
        "- formal `VERIFIED`: **0/164**.",
        "",
        "**Important:** `CONNECTIONS TRACED` is not `VERIFIED`.",
        "",
        "## Phase 3 — COMPLETE",
        "",
        "The durable Phase 3 graph/closure artifacts remain authoritative. Current known closure state is 164/164 connections traced, with the 554-edge v5 graph and Phase 3 quality gates already completed.",
        "",
        "## Phase 4 — Behavior & Enforcement",
        "",
        f"- behavior rows: **{rows}**;",
        f"- runtime observed: **{observed}/{rows}**;",
        f"- total pending stronger evidence: **{pending}**;",
        f"- current contradiction coverage: **{len(integrity.get('current_contradiction_ids', [])) - len(integrity.get('uncovered_current_contradiction_ids', []))}/{len(integrity.get('current_contradiction_ids', []))}**;",
        f"- skill breadth coverage: **{coverage.get('covered_skills', 0)}/{coverage.get('skill_denominator', 0)}**;",
        f"- high-risk non-SKILL surface coverage: **{coverage.get('covered_surfaces', 0)}/{coverage.get('surface_denominator', 0)}**;",
        "- Phase 4 hard errors: **0**.",
        "",
        "### Evidence-depth queue",
        "",
        f"- `EXECUTION_OBSERVATION`: **{observed_by.get('EXECUTION_OBSERVATION', 0)} observed / {pending_by.get('EXECUTION_OBSERVATION', 0)} pending**;",
        f"- `EXTERNAL_DEPENDENCY_VALIDATION`: **{observed_by.get('EXTERNAL_DEPENDENCY_VALIDATION', 0)} observed / {pending_by.get('EXTERNAL_DEPENDENCY_VALIDATION', 0)} pending**;",
        f"- `MACHINE_CONSUMER_VALIDATION`: **{observed_by.get('MACHINE_CONSUMER_VALIDATION', 0)} observed / {pending_by.get('MACHINE_CONSUMER_VALIDATION', 0)} pending**;",
        f"- `PROMPT_REDTEAM_LATER`: **{observed_by.get('PROMPT_REDTEAM_LATER', 0)} observed / {pending_by.get('PROMPT_REDTEAM_LATER', 0)} pending**.",
        "",
        "### Behavior state counts",
        "",
    ]

    for key in sorted(state_counts):
        lines.append(f"- `{key}`: **{state_counts[key]}**")

    lines += ["", "### Machine-enforcement counts", ""]
    for key in ("True", "PARTIAL", "False"):
        if key in machine_counts:
            lines.append(f"- `{key}`: **{machine_counts[key]}**")

    lines += [
        "",
        "Breadth coverage does not imply runtime verification. No Phase 4 row is sufficient for `VERIFIED` by itself.",
        "",
        "## Phase 5+ status",
        "",
        "- Phase 5 History: **IN PROGRESS**; currently registered H-events may be reconciled while contradiction-specific lineage can still remain.",
        "- Phase 6 Contradictions & Orphans: **IN PROGRESS**.",
        "- Phase 7 Runtime & Distribution: **IN PROGRESS**.",
        "- Phase 8 Second Pass: **NOT STARTED formally**.",
        "- Phase 9 Red-Team Verification: **NOT STARTED formally**.",
        "- Phase 10 System Reconstruction & KP Comparison: **BLOCKED by prior gates**.",
        "",
        "## Tooling ledger",
        "",
        f"Latest published durable classifier snapshot: **{tooling.get('incident_entry_count', 0)} incident entries** from **{tooling.get('failed_run_count', 0)} failed + {tooling.get('cancelled_run_count', 0)} cancelled runs**.",
        "",
        f"- unknown entries: **{tooling.get('unknown_entries', 0)}**;",
        f"- unresolved/review-required entries: **{tooling.get('unresolved_entries', 0)}**.",
        "",
        "The classifier preserves a previously published closed classification for the identical historical run + failed step when GitHub temporarily cannot return that old job log. New or previously open incidents still fail closed.",
        "",
        "## Immediate next execution",
        "",
        "1. Complete contradiction-specific lineage: bind each current CT record to exact history evidence or an explicit no-material-history disposition.",
        "2. Perform the formal second pass on high-impact operative, support, configuration, and distribution surfaces using the completed graph/history context.",
        "3. Run static red-team checks for universal, exclusivity, and numerical claims that can be disproved without an agent harness.",
        "4. Keep execution, machine-consumer, external-dependency, and prompt/red-team evidence classes separate; the pending execution observations are deferred because no supported agent runtime is available.",
        "5. Do not advance `VERIFIED` until all applicable Phase 4–9 gates close for the relevant claim/file.",
        "",
        "## Resume instruction",
        "",
        "Reload GitHub first. At minimum inspect:",
        "",
        "1. `00_RESEARCH_MANIFEST.md`",
        "2. `00_RESEARCH_SCHEMA.md`",
        "3. `RESEARCH_STATUS.md`",
        "4. `00_FOUNDATION_INTEGRITY.json`",
        "5. `00_TOOLING_FAILURE_LEDGER.json`",
        "6. `01_FILE_CENSUS.json`",
        "7. `03_CONNECTION_EDGES.json`",
        "8. `03_PHASE3_QUALITY.json`",
        "9. `04_BEHAVIOR_MATRIX.json`",
        "10. `04_BEHAVIOR_INTEGRITY.json`",
        "11. `04_BEHAVIOR_COVERAGE.json`",
        "12. `04_RUNTIME_OBSERVATION_QUEUE.json`",
        "13. `04_CONTRADICTION_REGISTER.md`",
        "14. `05_HISTORY_LEDGER.md`",
        "",
        "Do not resume from ChatGPT memory or chat summaries as authoritative state.",
        "",
    ]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} from authoritative machine artifacts: runtime={observed}/{rows}, pending={pending}, tooling_unknown={tooling.get('unknown_entries', 0)}")


if __name__ == "__main__":
    main()
